/*
 * Employee main screen v 1 - The main screen form where an employee type user
 * can manage the cases for the baggage
 */
package bagawareapp;

/**
 *
 * @author Team2FYS - IS106
 */
import static bagawareapp.LogonScreen.locationOfLogin;
import static bagawareapp.LogonScreen.usernameOfLogin;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jens
 */
public class EmployeeMainScreen extends javax.swing.JFrame {

    /**
     * declaration of variables, also makes a stringbuilder to be used later
     */
    public static StringBuilder labelCodeSelected = new StringBuilder();
    private Connection conn = null;
    private ResultSet rs1 = null;
    private ResultSet rs2 = null;
    private PreparedStatement pst = null;
    public static ResultSet rsmatch = null;
    private ResultSet rs = null;
    private JavaConnect JavaConnect = new JavaConnect();

    /**
     * @description Creates new form ManagerPopupScreen
     */
    EmployeeMainScreen() {
        initComponents();
        conn = JavaConnect.ConnecrDb();
        Update_Table_Bag();
        Update_Table_Client();
    }

    /**
     * @description method to fill the BAG table with data
     */
    private void Update_Table_Bag() {
        try {
            conn = JavaConnect.ConnecrDb();
            String sql = "SELECT baglabelcode AS 'Bagage Label', Status, "
                    + "Datecreated AS 'Created On'"
                    + "FROM bagawaredb.FOUND";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tableCasesBag.setModel(DbUtils.resultSetToTableModel(rs));
            JavaConnect.closeDb();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @description Method to fill the CLIENT table with data
     */
    private void Update_Table_Client() {
        try {
            conn = JavaConnect.ConnecrDb();
            String sql = "SELECT baglabelcode AS 'Bagage Label', Status, "
                    + "Datecreated AS 'Created On'"
                    + "FROM bagawaredb.LOST";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tableCasesClient.setModel(DbUtils.resultSetToTableModel(rs));
            JavaConnect.closeDb();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @description Method that checks the text in the search box and makes the
     * results appear in the table
     */
    private void TableSearch() {
        try {
            conn = JavaConnect.ConnecrDb();
            String sql = "SELECT * FROM bagawaredb.FOUND WHERE (baglabelcode=?"
                    + " OR brand=? OR color=? OR weight=?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            pst.setString(2, txt_search.getText());
            pst.setString(3, txt_search.getText());
            pst.setString(4, txt_search.getText());
            rs = pst.executeQuery();
            tableCasesClient.setModel(DbUtils.resultSetToTableModel(rs));
            tableCasesBag.setModel(DbUtils.resultSetToTableModel(rs));
            JavaConnect.closeDb();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        button_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        button_refresh = new javax.swing.JButton();
        button_search = new javax.swing.JButton();
        button_newcase = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCasesClient = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCasesBag = new javax.swing.JTable();
        button_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(159, 13, 10));
        headerPanel.setForeground(new java.awt.Color(159, 13, 10));
        headerPanel.setToolTipText("");
        headerPanel.setPreferredSize(new java.awt.Dimension(653, 140));

        button_logout.setText("Logout");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bagawareapp/logo - Small.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Service employee");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Logged in as:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText(usernameOfLogin);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Location:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText(locationOfLogin);

        button_refresh.setText("Refresh");
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_logout)))
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_refresh))
                        .addGap(18, 18, 18)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(53, 53, 53))
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(headerPanelLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(31, Short.MAX_VALUE))))))
        );

        button_search.setText("Search");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        button_newcase.setText("New case");
        button_newcase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_newcaseActionPerformed(evt);
            }
        });

        tableCasesClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Case ID (Client)", "Status", "Created on"
            }
        ));
        tableCasesClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCasesClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCasesClient);

        tableCasesBag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Case ID (Bag)", "Status", "Created on"
            }
        ));
        tableCasesBag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCasesBagMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCasesBag);

        button_delete.setText("Delete case");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_newcase, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search)
                    .addComponent(button_newcase)
                    .addComponent(button_delete))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * @description Log out and open login screen
     *
     * @param evt
     */
    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        //close current window
        this.dispose();
        //reopen the loginscreen
        LogonScreen login = new LogonScreen();
        login.setTitle("BagAware - Login Screen");      // title (of loginscreen) at logout
        login.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            // these lines force the login screen to the foreground and center it
            public void run() {
                login.toFront();
                login.repaint();
                login.setLocationRelativeTo(null);
            }
        });
    }//GEN-LAST:event_button_logoutActionPerformed
    /**
     * @description opens a new window where the user can pick the type of case
     * to be made
     * @param evt
     */
    private void button_newcaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_newcaseActionPerformed
        //Open the window to create a new case
        CasePopupNew cCreate = new CasePopupNew();
        cCreate.setTitle("BagAware - Create A New Case");   // set title
        cCreate.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // when (X) button is pressed, closes only the popup
        cCreate.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            // these lines force the screen to the foreground and centere it
            public void run() {
                cCreate.toFront();
                cCreate.repaint();
                cCreate.setLocationRelativeTo(null);
            }
        });
    }//GEN-LAST:event_button_newcaseActionPerformed
    /**
     * @description selects the entry in the client table, cancels selection in
     * the bag table
     * @param evt
     */
    private void tableCasesClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCasesClientMouseClicked

        try {
            tableCasesBag.getSelectionModel().clearSelection();
            conn = JavaConnect.ConnecrDb();
            int row = tableCasesClient.getSelectedRow();
            String tableClick = (String) (tableCasesClient.getModel().getValueAt(row, 0));
            String sql = "SELECT * FROM bagawaredb.FOUND WHERE baglabelcode='"
                    + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {

                String add1 = rs.getString("baglabelcode");
                labelCodeSelected = null;
                labelCodeSelected.append(add1);
            }
            JavaConnect.closeDb();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_tableCasesClientMouseClicked
    /**
     * @description opens the delete window
     * @param evt
     */
    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        CasePopupDelete cDelete = new CasePopupDelete();
        cDelete.setTitle("BagAware - Delete A Case");   // set title
        cDelete.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // when (X) button is pressed, closes only the popup
        cDelete.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            // these lines force the screen to the foreground and centere it
            public void run() {
                cDelete.toFront();
                cDelete.repaint();
                cDelete.setLocationRelativeTo(null);
            }
        });
    }//GEN-LAST:event_button_deleteActionPerformed
    /**
     * @description calls the tablesearch() method when button is pressed
     * @param evt
     */
    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        TableSearch();
    }//GEN-LAST:event_button_searchActionPerformed

    /**
     * @description Makes the table non-editable, only selectable
     * @param evt
     */
    private void headerPanelMouseReleased(java.awt.event.MouseEvent evt) {
        if (tableCasesBag.isEditing()) {
            tableCasesBag.getCellEditor().stopCellEditing();
        }
        tableCasesBag.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);

        if (tableCasesClient.isEditing()) {
            tableCasesClient.getCellEditor().stopCellEditing();
        }
        tableCasesClient.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
    }

    /**
     * @description refreshes the tables and fills them with new data
     * @param evt
     */
    private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refreshActionPerformed
        //refreshes the screen and table contents
        EmployeeMainScreen EMain = new EmployeeMainScreen();
        EMain.setTitle("Employee Main Screen");        // set title
        EMain.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            // these lines force the screen to the foreground and centere it
            public void run() {
                EMain.toFront();
                EMain.repaint();
                EMain.setLocationRelativeTo(null);
            }
        });
        this.dispose();
    }//GEN-LAST:event_button_refreshActionPerformed

    /**
     * @description selects entry in bag table if clicked and unselects selected
     * entry in client table
     * @param evt
     */
    private void tableCasesBagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCasesBagMouseClicked

        try {

            tableCasesClient.getSelectionModel().clearSelection();
            conn = JavaConnect.ConnecrDb();
            int row = tableCasesBag.getSelectedRow();
            String tableClick = (String) (tableCasesBag.getModel().getValueAt(row, 0));
            String sql = "SELECT * FROM bagawaredb.LOST WHERE baglabelcode='"
                    + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {

                String add1 = rs.getString("baglabelcode");
                labelCodeSelected = null;
                labelCodeSelected.append(add1);
            }
            JavaConnect.closeDb();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_tableCasesBagMouseClicked
    /**
     * @description Makes the app look for matches every time a window is closed
     * and focus on this window is gained
     * @param evt
     */
    private void formFocusGained(java.awt.event.FocusEvent evt) {
        findMatches();
    }

    /**
     * Method looks in the database for matching entries in the LOST and FOUND
     * tables and shows results in table
     */
    public void findMatches() {
        try {
            conn = JavaConnect.ConnecrDb();

            String sql1 = "SELECT baglabelcode FROM bagawaredb.LOST";
            String sql2 = "SELECT baglabelcode FROM bagawaredb.FOUND";

            pst = conn.prepareStatement(sql1);
            rs1 = pst.executeQuery();
            pst = conn.prepareStatement(sql2);
            rs2 = pst.executeQuery();

            if (rs1.equals(rs2)) {
                JOptionPane.showMessageDialog(null, "Match found for " + sql1);
                //update tabel with match
                String sql = "SELECT (baglabelcode, status, datecreated) FROM"
                        + " bagawaredb.FOUND WHERE baglabelcode =?";
                pst = conn.prepareStatement(sql1);
                pst.setString(1, sql1);
                rsmatch = pst.executeQuery();
                tableCasesClient.setModel(DbUtils.resultSetToTableModel(rs));
            } else {

                sql1 = "SELECT brand, color FROM bagawaredb.LOST";
                sql2 = "SELECT brand, color FROM bagawaredb.FOUND";

                pst = conn.prepareStatement(sql1);
                rs1 = pst.executeQuery();
                pst = conn.prepareStatement(sql2);
                rs2 = pst.executeQuery();

                if (rs1.equals(rs2)) {
                    String sql = "SELECT (baglabelcode, status, datecreated)"
                            + " FROM bagawaredb.FOUND WHERE brand =?";
                    pst = conn.prepareStatement(sql1);
                    pst.setString(1, sql1);
                    rsmatch = pst.executeQuery();
                    tableCasesClient.setModel(DbUtils.resultSetToTableModel(rs));
                } else {

                    sql1 = "SELECT weight FROM bagawaredb.LOST";
                    sql2 = "SELECT weight color FROM bagawaredb.FOUND";

                    pst = conn.prepareStatement(sql1);
                    rs1 = pst.executeQuery();
                    pst = conn.prepareStatement(sql2);
                    rs2 = pst.executeQuery();

                    if (rs1.equals(rs2)) {
                        String sql = "SELECT (baglabelcode, status, datecreated)"
                                + " FROM bagawaredb.FOUND WHERE brand =?";
                        pst = conn.prepareStatement(sql1);
                        pst.setString(1, sql1);
                        rsmatch = pst.executeQuery();
                        tableCasesClient.setModel(DbUtils.resultSetToTableModel(rs));
                        tableCasesBag.setModel(DbUtils.resultSetToTableModel(rs));
                    } else {
                        JOptionPane.showMessageDialog(null, "No matches found");
                    }
                }
            }

            JavaConnect.closeDb();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_newcase;
    private javax.swing.JButton button_refresh;
    private javax.swing.JButton button_search;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCasesBag;
    private javax.swing.JTable tableCasesClient;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
