/*
 * Loginscreen.java V 1 - A loginscreen where the user can acces the app, it 
 * will redirect the user to a mainscreen depending on their user type
 */
package bagawareapp;

/**
 *
 * @author Team2FYS - IS106
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;

public class LogonScreen extends javax.swing.JFrame {
//Prepare variables for future use (or in later screens)

    public static String locationOfLogin = null;
    public static String usernameOfLogin = null;
    public static String typeOfLogin = null;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    JavaConnect JavaConnect = new JavaConnect();
    
    LogonScreen() {
        initComponents();        
        conn = JavaConnect.ConnecrDb();
        //add locations to the combobox via method
        FillLocationBox();
        JavaConnect.closeDb();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * NetBeans autocode for the layout of the login screen
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logonpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmd_login = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        combobox_location = new java.awt.Choice();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logonpanel.setName("Login"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(156, 10, 13));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bagawareapp/logo - Small.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 266, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        cmd_login.setText("Login");
        cmd_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_loginActionPerformed(evt);
            }
        });

        exitbutton.setText("Cancel");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        combobox_location.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combobox_locationKeyPressed(evt);
            }
        });

        jLabel4.setText("Location");

        javax.swing.GroupLayout logonpanelLayout = new javax.swing.GroupLayout(logonpanel);
        logonpanel.setLayout(logonpanelLayout);
        logonpanelLayout.setHorizontalGroup(
            logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logonpanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(cmd_login, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logonpanelLayout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(exitbutton)
                    .addContainerGap(173, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(255, Short.MAX_VALUE)
                    .addComponent(combobox_location, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(256, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(84, Short.MAX_VALUE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(171, Short.MAX_VALUE)))
        );
        logonpanelLayout.setVerticalGroup(
            logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logonpanelLayout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 135, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(141, Short.MAX_VALUE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(cmd_login)
                    .addContainerGap()))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(exitbutton)
                    .addContainerGap()))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(combobox_location, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap(117, Short.MAX_VALUE)))
            .addGroup(logonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logonpanelLayout.createSequentialGroup()
                    .addContainerGap(90, Short.MAX_VALUE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_loginActionPerformed

        // To use the cmd_loginActionPerformed() method on multiple places in 
        // the code, we are referencing to the loginMethod() method
        loginMethod();
//*/
    }//GEN-LAST:event_cmd_loginActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        //close if cancel is pressed
        System.exit(0);

    }//GEN-LAST:event_exitbuttonActionPerformed

    // Log in when "enter" button is pressed
    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginMethod();
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void combobox_locationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combobox_locationKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginMethod();
        }
    }//GEN-LAST:event_combobox_locationKeyPressed
    //method to add locations into the combobox on the login screen

    private void FillLocationBox() {
        try {
            
            conn = JavaConnect.ConnecrDb();
            String sqlLocation = "SELECT * FROM bagawaredb.LOCATION";
            pst = conn.prepareStatement(sqlLocation);
            rs = pst.executeQuery();

            while (rs.next()) {
                String location = rs.getString("locationcode");
                combobox_location.addItem(location);

            }
        JavaConnect.closeDb();
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Connection to database failed,"
                    + " cannot fill location box");

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogonScreen().setVisible(true);

            }
        });
    }

    //---------------------------------------
    // The method that logs in the user, this method is used by the "login"
    // button in the login screen and the <enter> key also triggers this method
    private void loginMethod() {
        
        conn = JavaConnect.ConnecrDb();
        // login button logic is here
        String sqllogin = "select * from bagawaredb.ACCOUNT where username=?"
                + " and password=?";
        String resultSetAsString = null;
        locationOfLogin = (String) combobox_location.getSelectedItem();
        usernameOfLogin = txt_username.getText();
        try {

            pst = conn.prepareStatement(sqllogin);
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());

            rs = pst.executeQuery();
            if (rs.next()) {

                String sqlAccountType = "select TYPE_typecode from"
                        + " bagawaredb.ACCOUNT where username=? and password=?";
                pst = conn.prepareStatement(sqlAccountType);
                pst.setString(1, txt_username.getText());
                pst.setString(2, txt_password.getText());
                rs = pst.executeQuery();

                //make resultset (rs) into string
                while (rs.next()) {

                    resultSetAsString = rs.getString("TYPE_typecode");

                }

                //check account type and invoke the corresponding window
                if (resultSetAsString.equals("admin")) {
                    //assign type for later use
                    typeOfLogin = "admin";
                    //close the login screen
                    this.dispose();
                    //open the admin main screen
                    AdminMainScreen aMain = new AdminMainScreen();
                    aMain.setTitle("Administrator Main Screen");   // set title
                    aMain.setVisible(true);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        // these lines force the screen to the foreground
                        //and centere it
                        public void run() {
                            aMain.toFront();
                            aMain.repaint();
                            aMain.setLocationRelativeTo(null);
                        }
                    });

                } else if (resultSetAsString.equals("employee")) {
                    //assign type for later use
                    typeOfLogin = "employee";
                    //close the login screen
                    this.dispose();
                    //open the employee main screen
                    EmployeeMainScreen eMain = new EmployeeMainScreen();
                    eMain.setTitle("Employee Main Screen");        // set title
                    eMain.setVisible(true);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        // these lines force the screen to the foreground 
                        //and centere it
                        public void run() {
                            eMain.toFront();
                            eMain.repaint();
                            eMain.setLocationRelativeTo(null);
                        }
                    });

                } else if (resultSetAsString.equals("manager")) {
                    //assign type for later use
                    typeOfLogin = "manager";
                    //close the login screen
                    this.dispose();
                    //open the manager main screen
                    ManagerMainScreen mMain = new ManagerMainScreen();
                    mMain.setTitle("Manager Main Screen");         // set title
                    mMain.setVisible(true);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        // these lines force the screen to the foreground 
                        //and centere it
                        public void run() {
                            mMain.toFront();
                            mMain.repaint();
                            mMain.setLocationRelativeTo(null);
                        }
                    });

                } else {
                    //custom error in case a account in db has an unrecognised
                    //account type
                    JOptionPane.showMessageDialog(null, "Error, Type not found");
                }

            } else {
                //in case username and password are not found in database
                JOptionPane.showMessageDialog(null, "Username and password are"
                        + " incorrect");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection to login server"
                    + " failed");
        }
        //----------------------------------------
        
        JavaConnect.closeDb();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_login;
    private java.awt.Choice combobox_location;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel logonpanel;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
